language: javascript

before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

before_script:
 - 'npm install -g grunt-cli'
 - 'npm install --save-dev'

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 0c74d31e-bcf8-48c4-bb3b-cc7da491f5b3

script: grunt test
